<?php
  include 'enablecache.php';
?>
{
    "beers": [
        {
            "id": 1,
            "name": "Alvinne Mad Tom",
            "brewerId": 8,
            "styleId": 6,
            "abv": 4,
            "oakAged": false,
            "tags": "golden ale",
            "ratebeerId": 247366,
            "untappdId": 543791,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 4,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 2,
            "name": "Alvinne c'Moen",
            "brewerId": 8,
            "styleId": 12,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 1,
            "sweetness": 2,
            "acidity": 4
        },
        {
            "id": 3,
            "name": "Alvinne Land van Mortagne",
            "brewerId": 8,
            "styleId": 14,
            "abv": 12.8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 165719,
            "untappdId": 141500,
            "serving": 0,
            "colour": 2,
            "body": 4,
            "bitterness": 3,
            "sweetness": 4,
            "acidity": 1
        },
        {
            "id": 4,
            "name": "Alvinne Gentleman Sour Ale Oak Aged",
            "brewerId": 8,
            "styleId": 3,
            "abv": 11.5,
            "oakAged": true,
            "tags": "",
            "ratebeerId": 261754,
            "untappdId": 662165,
            "serving": 0,
            "colour": 4,
            "body": 3,
            "bitterness": 2,
            "sweetness": 3,
            "acidity": 2
        },
        {
            "id": 5,
            "name": "Alvinne Undressed Foederbier",
            "brewerId": 8,
            "styleId": 19,
            "abv": 6.9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 209865,
            "untappdId": 344283,
            "serving": 2,
            "colour": 4,
            "body": 2,
            "bitterness": 1,
            "sweetness": 2,
            "acidity": 3
        },
        {
            "id": 6,
            "name": "Alvinne Wild West Blackthorn Edition 2013",
            "brewerId": 8,
            "styleId": 3,
            "abv": 6,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": 270630,
            "untappdId": 781427,
            "serving": 2,
            "colour": 1,
            "body": 2,
            "bitterness": 1,
            "sweetness": 2,
            "acidity": 4
        },
        {
            "id": 7,
            "name": "Alvinne Alvino 2013",
            "brewerId": 8,
            "styleId": 3,
            "abv": 7,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": 100221,
            "untappdId": 169774,
            "serving": 2,
            "colour": 2,
            "body": 2,
            "bitterness": 1,
            "sweetness": 2,
            "acidity": 4
        },
        {
            "id": 8,
            "name": "Alvinne Kerasus 2013",
            "brewerId": 8,
            "styleId": 3,
            "abv": 6.9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 94439,
            "untappdId": 627370,
            "serving": 2,
            "colour": 3,
            "body": 2,
            "bitterness": 1,
            "sweetness": 2,
            "acidity": 4
        },
        {
            "id": 9,
            "name": "Alvinne Mano Negra Bourbon",
            "brewerId": 8,
            "styleId": 5,
            "abv": 10,
            "oakAged": true,
            "tags": "bourbon",
            "ratebeerId": 206761,
            "untappdId": 326627,
            "serving": 2,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 4,
            "acidity": 1
        },
        {
            "id": 10,
            "name": "Alvinne Mano Negra Chili Stout",
            "brewerId": 8,
            "styleId": 5,
            "abv": 10,
            "oakAged": true,
            "tags": "chili",
            "ratebeerId": 219536,
            "untappdId": 516943,
            "serving": 2,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 11,
            "name": "Alvinne Cuvée Sofie",
            "brewerId": 8,
            "styleId": 3,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 261753,
            "untappdId": 662302,
            "serving": 2,
            "colour": 1,
            "body": 3,
            "bitterness": 1,
            "sweetness": 3,
            "acidity": 3
        },
        {
            "id": 12,
            "name": "Alvinne Melchior",
            "brewerId": 8,
            "styleId": 1,
            "abv": 11,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 54472,
            "untappdId": 59782,
            "serving": 2,
            "colour": 2,
            "body": 3,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 13,
            "name": "Alvinne Phi",
            "brewerId": 8,
            "styleId": 3,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 247371,
            "untappdId": 558162,
            "serving": 2,
            "colour": 1,
            "body": 4,
            "bitterness": 1,
            "sweetness": 3,
            "acidity": 3
        },
        {
            "id": 14,
            "name": "Alvinne Sigma",
            "brewerId": 8,
            "styleId": 3,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 247376,
            "untappdId": 565503,
            "serving": 2,
            "colour": 4,
            "body": 3,
            "bitterness": 1,
            "sweetness": 3,
            "acidity": 3
        },
        {
            "id": 15,
            "name": "Alvinne Omega",
            "brewerId": 8,
            "styleId": 3,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 247375,
            "untappdId": 548937,
            "serving": 2,
            "colour": 1,
            "body": 2,
            "bitterness": 1,
            "sweetness": 2,
            "acidity": 3
        },
        {
            "id": 16,
            "name": "Brekeriet Barrique Rouge",
            "brewerId": 12,
            "styleId": 3,
            "abv": 9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 262837,
            "untappdId": 663167,
            "serving": 0,
            "colour": 3,
            "body": 3,
            "bitterness": 1,
            "sweetness": 3,
            "acidity": 4
        },
        {
            "id": 17,
            "name": "Brekeriet Brillant",
            "brewerId": 12,
            "styleId": 17,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 186662,
            "untappdId": 235713,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 2,
            "sweetness": 3,
            "acidity": 2
        },
        {
            "id": 18,
            "name": "Brekeriet Saison Sauvage",
            "brewerId": 12,
            "styleId": 3,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 262830,
            "untappdId": 235696,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 3
        },
        {
            "id": 20,
            "name": "BrewFist Terminal",
            "brewerId": 11,
            "styleId": 7,
            "abv": 3.7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 202737,
            "untappdId": 326843,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 21,
            "name": "BrewFist Beautiful and Strange Radler Edition",
            "brewerId": 11,
            "styleId": 12,
            "abv": 3.7,
            "oakAged": false,
            "tags": "gose",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 1,
            "sweetness": 1,
            "acidity": 4
        },
        {
            "id": 22,
            "name": "BrewFist Bionic",
            "brewerId": 11,
            "styleId": 2,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 252370,
            "untappdId": 595184,
            "serving": 0,
            "colour": 3,
            "body": 2,
            "bitterness": 4,
            "sweetness": 1,
            "acidity": 1
        },
        {
            "id": 23,
            "name": "BrewFist Spaceman",
            "brewerId": 11,
            "styleId": 2,
            "abv": 7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 144877,
            "untappdId": 53438,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 4,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 24,
            "name": "BrewFist Heimdall",
            "brewerId": 11,
            "styleId": 17,
            "abv": 7.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 222673,
            "untappdId": 489942,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 25,
            "name": "BrewFist 2Late",
            "brewerId": 11,
            "styleId": 1,
            "abv": 9.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 176821,
            "untappdId": 189124,
            "serving": 0,
            "colour": 2,
            "body": 3,
            "bitterness": 4,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 26,
            "name": "BrewFist Spaghetti Western",
            "brewerId": 11,
            "styleId": 5,
            "abv": 8.7,
            "oakAged": false,
            "tags": "chocolate,coffee",
            "ratebeerId": 250046,
            "untappdId": 519016,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 27,
            "name": "BrewFist X-Ray Barbera Barrel",
            "brewerId": 11,
            "styleId": 11,
            "abv": 8.5,
            "oakAged": true,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 2
        },
        {
            "id": 28,
            "name": "Burning Sky Aurora",
            "brewerId": 13,
            "styleId": 7,
            "abv": 5.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 235769,
            "untappdId": 480460,
            "serving": 0,
            "colour": 2,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 29,
            "name": "Burning Sky Devils Rest",
            "brewerId": 13,
            "styleId": 2,
            "abv": 7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 235770,
            "untappdId": 497238,
            "serving": 0,
            "colour": 3,
            "body": 3,
            "bitterness": 4,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 30,
            "name": "Burning Sky Saison L'Ete",
            "brewerId": 13,
            "styleId": 17,
            "abv": 4.2,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 273791,
            "untappdId": 736249,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 1,
            "sweetness": 1,
            "acidity": 2
        },
        {
            "id": 31,
            "name": "Burning Sky Saison à la Provision",
            "brewerId": 13,
            "styleId": 17,
            "abv": 6.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 235771,
            "untappdId": 501808,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 1,
            "sweetness": 1,
            "acidity": 3
        },
        {
            "id": 32,
            "name": "Burning Sky Monolith",
            "brewerId": 13,
            "styleId": 3,
            "abv": 7.4,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 3,
            "bitterness": 4,
            "sweetness": 1,
            "acidity": 3
        },
        {
            "id": 33,
            "name": "Burning Sky Arise",
            "brewerId": 13,
            "styleId": 12,
            "abv": 4.4,
            "oakAged": false,
            "tags": "session ipa",
            "ratebeerId": 271574,
            "untappdId": 697745,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 34,
            "name": "Burning Sky Plateau",
            "brewerId": 13,
            "styleId": 7,
            "abv": 3.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 235764,
            "untappdId": 480236,
            "serving": 1,
            "colour": 1,
            "body": 2,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 35,
            "name": "Ducato Viaemilia",
            "brewerId": 14,
            "styleId": 13,
            "abv": 5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 79805,
            "untappdId": 26541,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 36,
            "name": "Ducato Violent Femme",
            "brewerId": 14,
            "styleId": 17,
            "abv": 4.2,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 275730,
            "untappdId": 740682,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 37,
            "name": "Ducato Machete",
            "brewerId": 14,
            "styleId": 1,
            "abv": 7.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 159684,
            "untappdId": 159982,
            "serving": 0,
            "colour": 2,
            "body": 2,
            "bitterness": 4,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 38,
            "name": "Ducato La Luna Rossa",
            "brewerId": 14,
            "styleId": 3,
            "abv": 8,
            "oakAged": false,
            "tags": "kriek",
            "ratebeerId": 124170,
            "untappdId": 34767,
            "serving": 1,
            "colour": 3,
            "body": 2,
            "bitterness": 1,
            "sweetness": 2,
            "acidity": 5
        },
        {
            "id": 39,
            "name": "Ducato Frambozschella",
            "brewerId": 14,
            "styleId": 3,
            "abv": 5,
            "oakAged": false,
            "tags": "framboise",
            "ratebeerId": 234348,
            "untappdId": 481311,
            "serving": 1,
            "colour": 3,
            "body": 1,
            "bitterness": 2,
            "sweetness": 1,
            "acidity": 4
        },
        {
            "id": 40,
            "name": "Ducato Victoria",
            "brewerId": 14,
            "styleId": 2,
            "abv": 3.5,
            "oakAged": false,
            "tags": "session ipa",
            "ratebeerId": 125328,
            "untappdId": 226285,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 41,
            "name": "Ducato Vliegende Verdi",
            "brewerId": 14,
            "styleId": 5,
            "abv": 9.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 281320,
            "untappdId": 747207,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 4,
            "acidity": 1
        },
        {
            "id": 42,
            "name": "Ducato Chrysopolis RADLER (Rare AnD Limited Edition Radler)",
            "brewerId": 14,
            "styleId": 12,
            "abv": 5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 1,
            "colour": 1,
            "body": 1,
            "bitterness": 1,
            "sweetness": 1,
            "acidity": 5
        },
        {
            "id": 43,
            "name": "Emelisse XXV Black & Tan",
            "brewerId": 1,
            "styleId": 5,
            "abv": 25,
            "oakAged": false,
            "tags": "mix,eisbock",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 44,
            "name": "Emelisse White Label Barley Wine Makers Mark",
            "brewerId": 1,
            "styleId": 0,
            "abv": 11,
            "oakAged": true,
            "tags": "bourbon, makers mark",
            "ratebeerId": 257284,
            "untappdId": 655969,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 45,
            "name": "Emelisse White Label Imperial Russian Stout Rumba",
            "brewerId": 1,
            "styleId": 5,
            "abv": 11,
            "oakAged": true,
            "tags": "rum,rumba",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 46,
            "name": "Emelisse Earl Grey IPA",
            "brewerId": 1,
            "styleId": 2,
            "abv": 6.8,
            "oakAged": false,
            "tags": "tea",
            "ratebeerId": 252319,
            "untappdId": 728841,
            "serving": 2,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 47,
            "name": "Emelisse White Label Barley Wine Cognac",
            "brewerId": 1,
            "styleId": 0,
            "abv": 15,
            "oakAged": true,
            "tags": "cognac",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 48,
            "name": "Emelisse Aceto Balsamico #2",
            "brewerId": 1,
            "styleId": 19,
            "abv": 8,
            "oakAged": true,
            "tags": "balsamisco",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 2,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 49,
            "name": "Emelisse Black & Tan",
            "brewerId": 1,
            "styleId": 5,
            "abv": 10,
            "oakAged": true,
            "tags": "mix,bourbon,wild turkey",
            "ratebeerId": 197098,
            "untappdId": 165391,
            "serving": 2,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 50,
            "name": "Emelisse BockFiets",
            "brewerId": 1,
            "styleId": 12,
            "abv": 4,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 51,
            "name": "Emelisse White Label Imperial Russion Stout Makers Mark",
            "brewerId": 1,
            "styleId": 5,
            "abv": 11,
            "oakAged": true,
            "tags": "bourbon,makers mark",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 52,
            "name": "Emelisse White Label White Wine",
            "brewerId": 1,
            "styleId": 10,
            "abv": 8,
            "oakAged": true,
            "tags": "wine",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 53,
            "name": "h.ertie / Emelisse Sour Stout",
            "brewerId": 1,
            "styleId": 3,
            "abv": -1,
            "oakAged": false,
            "tags": "mix",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 2,
            "colour": 5,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 54,
            "name": "Evil Twin Femme Fatale Blanc",
            "brewerId": 15,
            "styleId": 2,
            "abv": 6,
            "oakAged": false,
            "tags": "brett",
            "ratebeerId": 208158,
            "untappdId": 334665,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 55,
            "name": "Evil Twin Femme Yuzu",
            "brewerId": 15,
            "styleId": 2,
            "abv": 6,
            "oakAged": false,
            "tags": "brett,fruit",
            "ratebeerId": 228840,
            "untappdId": 436479,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 56,
            "name": "Evil Twin Femme Sudachi",
            "brewerId": 15,
            "styleId": 2,
            "abv": 6,
            "oakAged": false,
            "tags": "brett,fruit",
            "ratebeerId": 280679,
            "untappdId": 745378,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 57,
            "name": "Evil Twin Femme Kabosu",
            "brewerId": 15,
            "styleId": 2,
            "abv": 6,
            "oakAged": false,
            "tags": "brett,fruit",
            "ratebeerId": 280678,
            "untappdId": 753965,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 58,
            "name": "Evil Twin Imperial Donought",
            "brewerId": 15,
            "styleId": 5,
            "abv": 11.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 202247,
            "untappdId": 315858,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 59,
            "name": "Evil Twin Ron & The Beast",
            "brewerId": 15,
            "styleId": 17,
            "abv": 7,
            "oakAged": false,
            "tags": "brett",
            "ratebeerId": 156085,
            "untappdId": 93161,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 60,
            "name": "Evil Twin Nomader Weisse",
            "brewerId": 15,
            "styleId": 22,
            "abv": 4,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 270997,
            "untappdId": 581837,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 61,
            "name": "Evil Twin / Intangible Ales Sour Bikini",
            "brewerId": 15,
            "styleId": 3,
            "abv": 3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 280677,
            "untappdId": 190843,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 62,
            "name": "Kernel Radler - Grapefruit",
            "brewerId": 6,
            "styleId": 12,
            "abv": 2.5,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 2,
            "sweetness": 1,
            "acidity": 3
        },
        {
            "id": 63,
            "name": "Kernel Radler - Lime",
            "brewerId": 6,
            "styleId": 12,
            "abv": 2.5,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 2,
            "sweetness": 1,
            "acidity": 3
        },
        {
            "id": 64,
            "name": "Kernel Pale Ale",
            "brewerId": 6,
            "styleId": 7,
            "abv": 5.3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 65,
            "name": "Kernel Table Beer",
            "brewerId": 6,
            "styleId": 7,
            "abv": 3,
            "oakAged": false,
            "tags": "session ipa",
            "ratebeerId": 187863,
            "untappdId": 243048,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 66,
            "name": "Kernel India Pale Ale",
            "brewerId": 6,
            "styleId": 2,
            "abv": 7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 67,
            "name": "Kernel London Sour Cherry",
            "brewerId": 6,
            "styleId": 3,
            "abv": 3,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": -1,
            "untappdId": 267939,
            "serving": 0,
            "colour": 3,
            "body": 1,
            "bitterness": 1,
            "sweetness": 1,
            "acidity": 4
        },
        {
            "id": 68,
            "name": "Kernel Biere de Table Oak Aged Saison",
            "brewerId": 6,
            "styleId": 17,
            "abv": 4.2,
            "oakAged": true,
            "tags": "",
            "ratebeerId": 251533,
            "untappdId": 668016,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 1,
            "sweetness": 1,
            "acidity": 2
        },
        {
            "id": 69,
            "name": "Kernel Imperial Brown Stout Barrel Aged Auchentoshan",
            "brewerId": 6,
            "styleId": 5,
            "abv": 10.3,
            "oakAged": true,
            "tags": "whisky",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 4,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 70,
            "name": "Laugar Kiskale",
            "brewerId": 3,
            "styleId": 21,
            "abv": 7.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": 765646,
            "serving": 0,
            "colour": 4,
            "body": 3,
            "bitterness": 2,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 71,
            "name": "Laugar Aupa Tovarisch Oporto Edition",
            "brewerId": 3,
            "styleId": 5,
            "abv": 11,
            "oakAged": true,
            "tags": "wine",
            "ratebeerId": 230699,
            "untappdId": 462669,
            "serving": 0,
            "colour": 5,
            "body": 5,
            "bitterness": 1,
            "sweetness": 4,
            "acidity": 1
        },
        {
            "id": 72,
            "name": "Laugar Radler 1.0",
            "brewerId": 3,
            "styleId": 12,
            "abv": 4,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 1,
            "sweetness": 1,
            "acidity": 3
        },
        {
            "id": 73,
            "name": "Laugar Hopzale",
            "brewerId": 3,
            "styleId": 1,
            "abv": 9.2,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 278796,
            "untappdId": 754538,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 4,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 74,
            "name": "Laugar Aizkolai Crowbeer",
            "brewerId": 3,
            "styleId": 14,
            "abv": 10.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 4,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 75,
            "name": "Magic Rock Bearded Lady PX Barrel",
            "brewerId": 16,
            "styleId": 5,
            "abv": 10.5,
            "oakAged": true,
            "tags": "px",
            "ratebeerId": 263994,
            "untappdId": 691079,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 76,
            "name": "Magic Rock Bourbon Barrel Bearded Lady",
            "brewerId": 16,
            "styleId": 5,
            "abv": 10.5,
            "oakAged": true,
            "tags": "bourbon",
            "ratebeerId": 171160,
            "untappdId": 153631,
            "serving": 0,
            "colour": 5,
            "body": 5,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 77,
            "name": "Magic Rock Circus of Sour White Wine",
            "brewerId": 16,
            "styleId": 22,
            "abv": 3.5,
            "oakAged": true,
            "tags": "wine",
            "ratebeerId": 272412,
            "untappdId": 698866,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 1,
            "sweetness": 1,
            "acidity": 4
        },
        {
            "id": 78,
            "name": "Magic Rock Cannonball",
            "brewerId": 16,
            "styleId": 2,
            "abv": 7.4,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 12873,
            "untappdId": 61315,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 4,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 79,
            "name": "Magic Rock High Wire",
            "brewerId": 16,
            "styleId": 7,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 145149,
            "untappdId": 61700,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 80,
            "name": "Magic Rock Simpleton",
            "brewerId": 16,
            "styleId": 7,
            "abv": 2.6,
            "oakAged": false,
            "tags": "session ipa",
            "ratebeerId": 202990,
            "untappdId": 302759,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 81,
            "name": "Magic Rock Villainous",
            "brewerId": 16,
            "styleId": 2,
            "abv": 6.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 254964,
            "untappdId": 615296,
            "serving": 0,
            "colour": 3,
            "body": 3,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 82,
            "name": "Magic Rock Salty Kiss",
            "brewerId": 16,
            "styleId": 3,
            "abv": 4.1,
            "oakAged": false,
            "tags": "fruit,gose",
            "ratebeerId": 204494,
            "untappdId": 322150,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 1,
            "sweetness": 2,
            "acidity": 3
        },
        {
            "id": 83,
            "name": "Magic Rock Magic 8 Ball",
            "brewerId": 16,
            "styleId": 8,
            "abv": 7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 163418,
            "untappdId": 121293,
            "serving": 0,
            "colour": 5,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 84,
            "name": "Magic Rock Dark Arts",
            "brewerId": 16,
            "styleId": 4,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 145150,
            "untappdId": 60245,
            "serving": 0,
            "colour": 5,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 85,
            "name": "Magic Rock Carnival",
            "brewerId": 16,
            "styleId": 6,
            "abv": 4.3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 171161,
            "untappdId": 60245,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 86,
            "name": "Magic Rock Rapture",
            "brewerId": 16,
            "styleId": 15,
            "abv": 4.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 145148,
            "untappdId": 62903,
            "serving": 1,
            "colour": 3,
            "body": 3,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 87,
            "name": "Magic Rock High Wire Cask",
            "brewerId": 16,
            "styleId": 7,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 145149,
            "untappdId": 61700,
            "serving": 1,
            "colour": 1,
            "body": 3,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 88,
            "name": "Närke Rainbow Warrior",
            "brewerId": 9,
            "styleId": 2,
            "abv": 7.8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 74865,
            "untappdId": 67943,
            "serving": 0,
            "colour": 1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 89,
            "name": "Närke Närke Slättöl",
            "brewerId": 9,
            "styleId": 7,
            "abv": 4.9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 49426,
            "untappdId": 56749,
            "serving": 0,
            "colour": 1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 90,
            "name": "Närke InterNationAle",
            "brewerId": 9,
            "styleId": 2,
            "abv": 7.2,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 31682,
            "untappdId": 92488,
            "serving": 0,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 91,
            "name": "Närke Örebro Bitter",
            "brewerId": 9,
            "styleId": 6,
            "abv": 5.9,
            "oakAged": false,
            "tags": "esb",
            "ratebeerId": 44034,
            "untappdId": 55422,
            "serving": 0,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 92,
            "name": "Närke Älj-Äjl",
            "brewerId": 9,
            "styleId": 9,
            "abv": 6.9,
            "oakAged": false,
            "tags": "herbs spices",
            "ratebeerId": 186933,
            "untappdId": 236467,
            "serving": 0,
            "colour": 1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 93,
            "name": "Närke Huvill",
            "brewerId": 9,
            "styleId": 2,
            "abv": 8.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 46968,
            "untappdId": 54217,
            "serving": 0,
            "colour": 1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 94,
            "name": "Närke Peated Viking",
            "brewerId": 9,
            "styleId": 6,
            "abv": 5.8,
            "oakAged": false,
            "tags": "smoked",
            "ratebeerId": 117236,
            "untappdId": 54214,
            "serving": 0,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 95,
            "name": "Närke Tanngnjost & Tanngrisnir",
            "brewerId": 9,
            "styleId": 9,
            "abv": 6.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 112558,
            "untappdId": 8639,
            "serving": 0,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 96,
            "name": "Närke Skvatt Galen",
            "brewerId": 9,
            "styleId": 9,
            "abv": 5.9,
            "oakAged": false,
            "tags": "herbs spices",
            "ratebeerId": 130786,
            "untappdId": 75520,
            "serving": 0,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 97,
            "name": "Närke Svarte Kungen",
            "brewerId": 9,
            "styleId": 11,
            "abv": 7.3,
            "oakAged": false,
            "tags": "mix",
            "ratebeerId": 71176,
            "untappdId": 362406,
            "serving": 0,
            "colour": 5,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 98,
            "name": "Närke Bäver",
            "brewerId": 9,
            "styleId": 6,
            "abv": 5.9,
            "oakAged": false,
            "tags": "castorium",
            "ratebeerId": 131490,
            "untappdId": 54227,
            "serving": 0,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 99,
            "name": "Närke / Oppigårds Ädelweiss",
            "brewerId": 9,
            "styleId": 20,
            "abv": 6.2,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": 769296,
            "serving": 0,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 100,
            "name": "Närke Unnamed Swedish Radler",
            "brewerId": 9,
            "styleId": 12,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": -1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 101,
            "name": "Gadds' Green Hop Ale",
            "brewerId": 17,
            "styleId": 7,
            "abv": 4.8,
            "oakAged": false,
            "tags": "session ipa",
            "ratebeerId": 133502,
            "untappdId": 76695,
            "serving": 1,
            "colour": 1,
            "body": 2,
            "bitterness": 4,
            "sweetness": 1,
            "acidity": 1
        },
        {
            "id": 102,
            "name": "Gadds' Green Radler",
            "brewerId": 17,
            "styleId": 12,
            "abv": 2.4,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 1,
            "colour": 1,
            "body": 1,
            "bitterness": 2,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 103,
            "name": "Tilquin Oude Gueuze Tilquin à l'ancienne",
            "brewerId": 18,
            "styleId": 23,
            "abv": 6.4,
            "oakAged": false,
            "tags": "gueuze",
            "ratebeerId": 144762,
            "untappdId": 59861,
            "serving": 2,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 104,
            "name": "Tilquin Oude Quetsche Tilquin à l'ancienne",
            "brewerId": 18,
            "styleId": 23,
            "abv": 6.4,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": 184008,
            "untappdId": 226919,
            "serving": 2,
            "colour": 3,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 105,
            "name": "Tilquin Gueuze Tilquin Draft",
            "brewerId": 18,
            "styleId": 23,
            "abv": 4.8,
            "oakAged": false,
            "tags": "gueuze",
            "ratebeerId": 152231,
            "untappdId": 186050,
            "serving": 1,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 106,
            "name": "Tilquin Stout Rulquin",
            "brewerId": 18,
            "styleId": 3,
            "abv": 7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 233726,
            "untappdId": 481403,
            "serving": 2,
            "colour": 5,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 107,
            "name": "Tilquin Faro",
            "brewerId": 18,
            "styleId": 24,
            "abv": 4.8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 145992,
            "untappdId": 83588,
            "serving": 1,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 108,
            "name": "Tilquin Oude (Gueuze Tilquin)² à l'ancienne",
            "brewerId": 18,
            "styleId": 23,
            "abv": 7.6,
            "oakAged": false,
            "tags": "gueuze",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 2,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 109,
            "name": "Tilquin Meerts Radler",
            "brewerId": 18,
            "styleId": 12,
            "abv": 3.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 1,
            "colour": 1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 110,
            "name": "Toccalmatto Radler",
            "brewerId": 20,
            "styleId": 12,
            "abv": 9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 4,
            "bitterness": 1,
            "sweetness": 3,
            "acidity": 3
        },
        {
            "id": 111,
            "name": "Toccalmatto Maciste",
            "brewerId": 20,
            "styleId": 1,
            "abv": 9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 123997,
            "untappdId": 33917,
            "serving": 0,
            "colour": 1,
            "body": 4,
            "bitterness": 5,
            "sweetness": 1,
            "acidity": 1
        },
        {
            "id": 112,
            "name": "Toccalmatto Zona Cesarini",
            "brewerId": 20,
            "styleId": 2,
            "abv": 6.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 3,
            "sweetness": 1,
            "acidity": 1
        },
        {
            "id": 113,
            "name": "Toccalmatto Delta Red Disorder",
            "brewerId": 20,
            "styleId": 15,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 2,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 114,
            "name": "Toccalmatto Hops Tripper",
            "brewerId": 20,
            "styleId": 21,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 4,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 115,
            "name": "Toccalmatto Tabularasa",
            "brewerId": 20,
            "styleId": 17,
            "abv": 5.3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 207439,
            "untappdId": 316755,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 3,
            "sweetness": 1,
            "acidity": 1
        },
        {
            "id": 116,
            "name": "Toccalmatto Dudes",
            "brewerId": 20,
            "styleId": 0,
            "abv": 12,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 169561,
            "untappdId": 140559,
            "serving": 2,
            "colour": 3,
            "body": 5,
            "bitterness": 1,
            "sweetness": 4,
            "acidity": 1
        },
        {
            "id": 117,
            "name": "Toccalmatto Salty Dog",
            "brewerId": 20,
            "styleId": 0,
            "abv": 12,
            "oakAged": true,
            "tags": "whisky,coal ila",
            "ratebeerId": 169562,
            "untappdId": 157311,
            "serving": 2,
            "colour": 3,
            "body": 5,
            "bitterness": 1,
            "sweetness": 4,
            "acidity": 1
        },
        {
            "id": 118,
            "name": "Toccalmatto Bedda Matri",
            "brewerId": 20,
            "styleId": 0,
            "abv": 12,
            "oakAged": true,
            "tags": "wine",
            "ratebeerId": 230735,
            "untappdId": 461007,
            "serving": 2,
            "colour": 3,
            "body": 5,
            "bitterness": 1,
            "sweetness": 4,
            "acidity": 1
        },
        {
            "id": 119,
            "name": "Toccalmatto Ombra",
            "brewerId": 20,
            "styleId": 18,
            "abv": 10,
            "oakAged": true,
            "tags": "grappa",
            "ratebeerId": 234241,
            "untappdId": 484239,
            "serving": 2,
            "colour": 2,
            "body": 5,
            "bitterness": 1,
            "sweetness": 4,
            "acidity": 1
        },
        {
            "id": 120,
            "name": "Toccalmatto Russian Imperial Stout Sagrantino di Montefalco Bretta BA",
            "brewerId": 20,
            "styleId": 5,
            "abv": 5,
            "oakAged": true,
            "tags": "wine,brett",
            "ratebeerId": 124460,
            "untappdId": 36226,
            "serving": 2,
            "colour": 5,
            "body": 5,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 121,
            "name": "Toccalmatto Black Bretty Wild Cerries/Bretta",
            "brewerId": 20,
            "styleId": 5,
            "abv": 9.5,
            "oakAged": true,
            "tags": "fruit,brett",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 2,
            "colour": 5,
            "body": 5,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 3
        },
        {
            "id": 122,
            "name": "Het Uiltje Bosuil - Tawny owl",
            "brewerId": 19,
            "styleId": 8,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 232053,
            "untappdId": 187163,
            "serving": 0,
            "colour": 5,
            "body": 3,
            "bitterness": 4,
            "sweetness": 1,
            "acidity": 1
        },
        {
            "id": 123,
            "name": "Het Uiltje Schreeuwuil - Screech owl",
            "brewerId": 19,
            "styleId": 1,
            "abv": 9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 216641,
            "untappdId": 239420,
            "serving": 0,
            "colour": 2,
            "body": 3,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 124,
            "name": "Het Uiltje Nothing Left of a Lager Caol Ila BA",
            "brewerId": 19,
            "styleId": 13,
            "abv": 5,
            "oakAged": true,
            "tags": "whisky,coal ila",
            "ratebeerId": -1,
            "untappdId": 733386,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 2,
            "sweetness": 1,
            "acidity": 1
        },
        {
            "id": 125,
            "name": "Het Uiltje Meneer de Uil Bowmore BA",
            "brewerId": 19,
            "styleId": 5,
            "abv": 11.5,
            "oakAged": true,
            "tags": "wisky,bowmore",
            "ratebeerId": 282779,
            "untappdId": 686136,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 126,
            "name": "Het Uiltje Meneer de Uil Mortlach BA",
            "brewerId": 19,
            "styleId": 5,
            "abv": 11.5,
            "oakAged": true,
            "tags": "11.5",
            "ratebeerId": -1,
            "untappdId": 686139,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 127,
            "name": "Het Uiltje Flaming Ass-Owl",
            "brewerId": 19,
            "styleId": 11,
            "abv": 9.7,
            "oakAged": false,
            "tags": "chili,smoked",
            "ratebeerId": 232055,
            "untappdId": 733388,
            "serving": 0,
            "colour": 5,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 128,
            "name": "Het Uiltje Black, Brett and Red ",
            "brewerId": 19,
            "styleId": 21,
            "abv": 10.5,
            "oakAged": false,
            "tags": "mix,brett",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 4,
            "body": 2,
            "bitterness": 2,
            "sweetness": 3,
            "acidity": 3
        },
        {
            "id": 129,
            "name": "Het Uiltje Uilezeik - Lime Viognier BA",
            "brewerId": 19,
            "styleId": 3,
            "abv": 6.5,
            "oakAged": false,
            "tags": "wine,fruit",
            "ratebeerId": 273373,
            "untappdId": 723165,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 4
        },
        {
            "id": 130,
            "name": "Het Uiltje Mind your step",
            "brewerId": 19,
            "styleId": 5,
            "abv": 14.8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": 733387,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 4,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 131,
            "name": "Het Uiltje Pepperspray Porter Carolina Reaper",
            "brewerId": 19,
            "styleId": 11,
            "abv": 8.6,
            "oakAged": false,
            "tags": "chili",
            "ratebeerId": 260239,
            "untappdId": 627839,
            "serving": 0,
            "colour": 5,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 132,
            "name": "Het Uiltje G and T Dryhopped Radler",
            "brewerId": 19,
            "styleId": 12,
            "abv": 2.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 4,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 133,
            "name": "Mont Salève Smoked IPA",
            "brewerId": 21,
            "styleId": 2,
            "abv": 6,
            "oakAged": false,
            "tags": "smoked",
            "ratebeerId": 281597,
            "untappdId": 772228,
            "serving": 0,
            "colour": 2,
            "body": 4,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 134,
            "name": "Mont Salève Berliner Weisse",
            "brewerId": 21,
            "styleId": 22,
            "abv": 3.3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 281596,
            "untappdId": 772229,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 1,
            "sweetness": 2,
            "acidity": 4
        },
        {
            "id": 135,
            "name": "Mont Salève Blueberries Radler Sour",
            "brewerId": 21,
            "styleId": 12,
            "abv": 3.6,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 3,
            "body": 2,
            "bitterness": 1,
            "sweetness": 1,
            "acidity": 3
        },
        {
            "id": 136,
            "name": "Mont Salève Stout Framboise",
            "brewerId": 21,
            "styleId": 4,
            "abv": 6.5,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": 249944,
            "untappdId": 543572,
            "serving": 0,
            "colour": 5,
            "body": 3,
            "bitterness": 1,
            "sweetness": 2,
            "acidity": 3
        },
        {
            "id": 137,
            "name": "Mont Salève Barrel Aged Gentian Gruit",
            "brewerId": 21,
            "styleId": 9,
            "abv": 6.5,
            "oakAged": true,
            "tags": "gruit",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 4,
            "sweetness": 1,
            "acidity": 3
        },
        {
            "id": 138,
            "name": "Mont Salève Black Indians",
            "brewerId": 21,
            "styleId": 8,
            "abv": 9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 253140,
            "untappdId": 583010,
            "serving": 0,
            "colour": 5,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 139,
            "name": "Mont Salève Barbe Rouge Mademoiselle",
            "brewerId": 21,
            "styleId": 2,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 268760,
            "untappdId": 699722,
            "serving": 0,
            "colour": 2,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 140,
            "name": "Mont Salève Fine de Merlot Rye Porter",
            "brewerId": 21,
            "styleId": 11,
            "abv": 5.5,
            "oakAged": true,
            "tags": "wine,rye",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 2,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 141,
            "name": "Rocket Brewing Total Eclipse",
            "brewerId": 22,
            "styleId": 4,
            "abv": 8.5,
            "oakAged": false,
            "tags": "oatmeal",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 2,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 142,
            "name": "Rocket Brewing Zero Gravity",
            "brewerId": 22,
            "styleId": 2,
            "abv": 6.7,
            "oakAged": false,
            "tags": "brett",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 2,
            "body": 2,
            "bitterness": 4,
            "sweetness": 1,
            "acidity": 1
        },
        {
            "id": 143,
            "name": "Rocket Brewing Club Trobicana",
            "brewerId": 22,
            "styleId": 7,
            "abv": 5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 4,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 144,
            "name": "Rocket Brewing Zaccharine Bourbon BA",
            "brewerId": 22,
            "styleId": 0,
            "abv": 8,
            "oakAged": true,
            "tags": "bourbon",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 3,
            "body": 4,
            "bitterness": 1,
            "sweetness": 4,
            "acidity": 1
        },
        {
            "id": 145,
            "name": "Rocket Brewing Monks on Mars",
            "brewerId": 22,
            "styleId": 10,
            "abv": 9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 146,
            "name": "Rocket Brewing First Contact",
            "brewerId": 22,
            "styleId": 17,
            "abv": 6.3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 3,
            "sweetness": 1,
            "acidity": 1
        },
        {
            "id": 147,
            "name": "Rocket Brewing Brown Dwarf",
            "brewerId": 22,
            "styleId": 1,
            "abv": 9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 2,
            "body": 3,
            "bitterness": 4,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 148,
            "name": "Rocket Brewing Hyper Nova",
            "brewerId": 22,
            "styleId": 19,
            "abv": 10.9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 4,
            "body": 2,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 4
        },
        {
            "id": 149,
            "name": "Rocket Brewing Super Nova",
            "brewerId": 22,
            "styleId": 19,
            "abv": 6.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 3,
            "body": 2,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 4
        },
        {
            "id": 150,
            "name": "Rocket Brewing Coffee Eclipse Cardamom",
            "brewerId": 22,
            "styleId": 4,
            "abv": 8.3,
            "oakAged": false,
            "tags": "coffee,oatmeal,herbs spices",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 2,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 151,
            "name": "De Molen Rasputin Bourbon BA",
            "brewerId": 0,
            "styleId": 5,
            "abv": 11,
            "oakAged": true,
            "tags": "bourbon",
            "ratebeerId": 220400,
            "untappdId": 568291,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 152,
            "name": "De Molen Dag & Nacht BA",
            "brewerId": 0,
            "styleId": 5,
            "abv": 11.3,
            "oakAged": true,
            "tags": "",
            "ratebeerId": 242108,
            "untappdId": 531251,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 153,
            "name": "De Molen Hel & Verdoemenis Wild Turkey BA Eisbock",
            "brewerId": 0,
            "styleId": 5,
            "abv": 20,
            "oakAged": true,
            "tags": "eisbock,bourbon,wild turkey",
            "ratebeerId": 230668,
            "untappdId": 460455,
            "serving": 0,
            "colour": 5,
            "body": 5,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 154,
            "name": "De Molen Hemel & Aarde Octomore BA",
            "brewerId": 0,
            "styleId": 5,
            "abv": 11,
            "oakAged": true,
            "tags": "wiskey,octomore",
            "ratebeerId": 281378,
            "untappdId": 777123,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 155,
            "name": "De Molen Lost & Found",
            "brewerId": 0,
            "styleId": 3,
            "abv": 6.6,
            "oakAged": true,
            "tags": "brett",
            "ratebeerId": 246564,
            "untappdId": 510853,
            "serving": 0,
            "colour": 5,
            "body": 3,
            "bitterness": 3,
            "sweetness": 1,
            "acidity": 3
        },
        {
            "id": 156,
            "name": "De Molen Mango IPA",
            "brewerId": 0,
            "styleId": 2,
            "abv": 5.8,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 157,
            "name": "De Molen Strawberry IPA",
            "brewerId": 0,
            "styleId": 2,
            "abv": 5.8,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 2,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 158,
            "name": "De Molen Habanero IPA",
            "brewerId": 0,
            "styleId": 2,
            "abv": 6.2,
            "oakAged": false,
            "tags": "chili",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 159,
            "name": "De Molen Friday Radler Lime",
            "brewerId": 0,
            "styleId": 12,
            "abv": 3.1,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 160,
            "name": "De Molen Saturday Radler Mint",
            "brewerId": 0,
            "styleId": 12,
            "abv": 3.1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 1,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 1
        },
        {
            "id": 161,
            "name": "De Molen Radler Rasputin Bourbon BA – Amarena",
            "brewerId": 0,
            "styleId": 12,
            "abv": 11.8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 4,
            "body": 4,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 162,
            "name": "De Molen Rasputin on Cherries Bourbon BA",
            "brewerId": 0,
            "styleId": 5,
            "abv": 11,
            "oakAged": true,
            "tags": "fruit,bourbon",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 163,
            "name": "De Molen / Zombier Hell & Zombier",
            "brewerId": 0,
            "styleId": 5,
            "abv": 9.1,
            "oakAged": false,
            "tags": "coffee",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 4,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 164,
            "name": "De Molen / Omnipollo Karl Framboise",
            "brewerId": 0,
            "styleId": 22,
            "abv": 5.5,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 3,
            "body": 2,
            "bitterness": 1,
            "sweetness": 1,
            "acidity": 3
        },
        {
            "id": 165,
            "name": "De Molen Twist & Stout Cognac BA",
            "brewerId": 0,
            "styleId": 5,
            "abv": 12,
            "oakAged": true,
            "tags": "cognac",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 5,
            "bitterness": 4,
            "sweetness": 4,
            "acidity": 1
        },
        {
            "id": 166,
            "name": "De Molen 21 Grams Anniversary Ale 10 Years de Molen",
            "brewerId": 0,
            "styleId": 1,
            "abv": 9.2,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 4,
            "bitterness": 5,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 167,
            "name": "De Molen Vlees & Bloed (light habanero, fleur de sel, heather honey B.F.)",
            "brewerId": 0,
            "styleId": 5,
            "abv": 10.9,
            "oakAged": false,
            "tags": "chili",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 5,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 168,
            "name": "De Molen Moord & Brand Bourbon and Bordeaux BA",
            "brewerId": 0,
            "styleId": 5,
            "abv": 9.8,
            "oakAged": true,
            "tags": "wine,bourbon",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 5,
            "body": 4,
            "bitterness": 3,
            "sweetness": 3,
            "acidity": 1
        },
        {
            "id": 169,
            "name": "De Molen Barley Bomb",
            "brewerId": 0,
            "styleId": 0,
            "abv": 10.7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 2,
            "body": 5,
            "bitterness": 4,
            "sweetness": 5,
            "acidity": 1
        },
        {
            "id": 170,
            "name": "De Molen / Emelisse Prachtig & Machtig",
            "brewerId": 0,
            "styleId": 0,
            "abv": 10.2,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 2,
            "body": 5,
            "bitterness": 2,
            "sweetness": 5,
            "acidity": 1
        },
        {
            "id": 171,
            "name": "Cantillon Gueuze",
            "brewerId": 23,
            "styleId": 23,
            "abv": 5,
            "oakAged": true,
            "tags": "",
            "ratebeerId": 6925,
            "untappdId": 56829,
            "serving": 0,
            "colour": 1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 172,
            "name": "Cantillon Young Lambic",
            "brewerId": 23,
            "styleId": 23,
            "abv": 5,
            "oakAged": true,
            "tags": "",
            "ratebeerId": 27965,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 173,
            "name": "Cantillon Old Lambic",
            "brewerId": 23,
            "styleId": 23,
            "abv": 5,
            "oakAged": true,
            "tags": "",
            "ratebeerId": 63328,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 174,
            "name": "Cantillon Rosé de Gambrinus",
            "brewerId": 23,
            "styleId": 23,
            "abv": 5,
            "oakAged": true,
            "tags": "fruit",
            "ratebeerId": 6014,
            "untappdId": 13142,
            "serving": 0,
            "colour": 3,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 175,
            "name": "Cantillon Kriek",
            "brewerId": 23,
            "styleId": 23,
            "abv": 5,
            "oakAged": true,
            "tags": "fruit",
            "ratebeerId": 6013,
            "untappdId": 36432,
            "serving": 0,
            "colour": 3,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 176,
            "name": "Cantillon Fou' Foune",
            "brewerId": 23,
            "styleId": 23,
            "abv": 5,
            "oakAged": true,
            "tags": "fruit",
            "ratebeerId": 7502,
            "untappdId": 17663,
            "serving": 0,
            "colour": 2,
            "body": -1,
            "bitterness": -1,
            "sweetness": -1,
            "acidity": -1
        },
        {
            "id": 177,
            "name": "Brekeriet Brunette",
            "brewerId": 12,
            "styleId": 19,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 278898,
            "untappdId": 758004,
            "serving": 0,
            "colour": 4,
            "body": 3,
            "bitterness": 2,
            "sweetness": 3,
            "acidity": 4
        },
        {
            "id": 178,
            "name": "Brekeriet Radler (Sour Rhubarb)",
            "brewerId": 12,
            "styleId": 12,
            "abv": -1,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 1,
            "sweetness": 4,
            "acidity": 4
        },
        {
            "id": 179,
            "name": "Brekeriet Cassis",
            "brewerId": 12,
            "styleId": 3,
            "abv": 5.2,
            "oakAged": false,
            "tags": "fruit,brett",
            "ratebeerId": 186661,
            "untappdId": 235699,
            "serving": 0,
            "colour": 3,
            "body": 3,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 3
        },
        {
            "id": 180,
            "name": "Brekeriet Sour Amber",
            "brewerId": 12,
            "styleId": 3,
            "abv": 6.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 281704,
            "untappdId": 778743,
            "serving": 0,
            "colour": 2,
            "body": 4,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 3
        },
        {
            "id": 181,
            "name": "Brekeriet Levain",
            "brewerId": 12,
            "styleId": 3,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 284925,
            "untappdId": 795910,
            "serving": 0,
            "colour": 1,
            "body": 2,
            "bitterness": 2,
            "sweetness": 2,
            "acidity": 5
        },
        {
            "id": 182,
            "name": "Brekeriet/Ängö Ängelbrekt",
            "brewerId": 12,
            "styleId": 3,
            "abv": -1,
            "oakAged": false,
            "tags": "märzen",
            "ratebeerId": -1,
            "untappdId": -1,
            "serving": 0,
            "colour": 2,
            "body": 4,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 3
        },
        {
            "id": 183,
            "name": "Brekeriet Xiyar",
            "brewerId": 12,
            "styleId": 17,
            "abv": 5,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": 256031,
            "untappdId": 620299,
            "serving": 2,
            "colour": 1,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 2
        },
        {
            "id": 184,
            "name": "Brekeriet Rubus",
            "brewerId": 12,
            "styleId": 3,
            "abv": 5.4,
            "oakAged": false,
            "tags": "fruit,brett",
            "ratebeerId": 256069,
            "untappdId": 620303,
            "serving": 2,
            "colour": 3,
            "body": 3,
            "bitterness": 3,
            "sweetness": 2,
            "acidity": 3
        }
    ],
    "revision": 22
}
