<?php
  include 'enablecache.php';
?>
{
    "beers": [
        {
            "id": 1,
            "name": "De Molen Plastic Soup BA",
            "brewerId": 0,
            "styleId": 3,
            "abv": 11,
            "oakAged": true,
            "tags": "barrel aged",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 2,
            "name": "De Molen Zure Kersen Bom",
            "brewerId": 0,
            "styleId": 3,
            "abv": 6.2,
            "oakAged": false,
            "tags": "cherry",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 3,
            "name": "De Molen Ginger Shot",
            "brewerId": 0,
            "styleId": 2,
            "abv": 4.2,
            "oakAged": false,
            "tags": "ginger",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 4,
            "name": "De Molen Moord & Brand Balsamico",
            "brewerId": 0,
            "styleId": 5,
            "abv": 9.8,
            "oakAged": true,
            "tags": "barrel aged,balsamico",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 5,
            "name": "De Molen Moord & Brand High Ester Rhum",
            "brewerId": 0,
            "styleId": 5,
            "abv": 9.8,
            "oakAged": true,
            "tags": "barrel aged,rum",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 6,
            "name": "De Molen Moord & Brand Bourbon BA",
            "brewerId": 0,
            "styleId": 5,
            "abv": 9.8,
            "oakAged": true,
            "tags": "barrel aged,bourbon",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 7,
            "name": "De Molen Hel & Verdoemenis Wild Turkey Eisbock",
            "brewerId": 0,
            "styleId": 5,
            "abv": 18,
            "oakAged": true,
            "tags": "barrel aged,bourbon,eisbock",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 8,
            "name": "De Molen Hot & Spicy III",
            "brewerId": 0,
            "styleId": 5,
            "abv": 10.2,
            "oakAged": false,
            "tags": "chilli",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 9,
            "name": "De Molen Hel & Verdoemenis Kopi Loewak",
            "brewerId": 0,
            "styleId": 5,
            "abv": 10,
            "oakAged": false,
            "tags": "coffee",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 10,
            "name": "De Molen Dutch Fresh Hopped",
            "brewerId": 0,
            "styleId": 2,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 11,
            "name": "De Molen Braggot BA",
            "brewerId": 0,
            "styleId": 16,
            "abv": 9,
            "oakAged": true,
            "tags": "barrel aged",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 12,
            "name": "Emelisse Barley Wine Buffalo Trace BA",
            "brewerId": 1,
            "styleId": 0,
            "abv": 12,
            "oakAged": true,
            "tags": "barrel aged,bourbon",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 13,
            "name": "Emelisse 2,5",
            "brewerId": 1,
            "styleId": 2,
            "abv": 2.5,
            "oakAged": false,
            "tags": "low alcohol",
            "ratebeerId": 176457,
            "untappdId": 190274
        },
        {
        	"id": 14,
            "name": "Emelisse XXV",
            "brewerId": 1,
            "styleId": 5,
            "abv": 25,
            "oakAged": false,
            "tags": "eisbock",
            "ratebeerId": 186716,
            "untappdId": 236483
        },
        {
        	"id": 15,
            "name": "Emelisse Imperial Russian Stout Wild Turkey BA",
            "brewerId": 1,
            "styleId": 5,
            "abv": 11,
            "oakAged": true,
            "tags": "barrel aged,bourbon",
            "ratebeerId": 200568,
            "untappdId": 315055
        },
        {
        	"id": 16,
            "name": "Emelisse Creme Brulee Stout",
            "brewerId": 1,
            "styleId": 4,
            "abv": 8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 17,
            "name": "Emelisse Aceto Balsamico BA",
            "brewerId": 1,
            "styleId": 5,
            "abv": 7.5,
            "oakAged": true,
            "tags": "barrel aged,balsamico",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 18,
            "name": "Emelisse Imperial Russian Stout Peated Bowmore BA",
            "brewerId": 1,
            "styleId": 5,
            "abv": 11,
            "oakAged": true,
            "tags": "barrel aged,wiskey",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 19,
            "name": "Emelisse Brett Bees",
            "brewerId": 1,
            "styleId": 16,
            "abv": 10,
            "oakAged": false,
            "tags": "brett",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 20,
            "name": "Emelisse Porter",
            "brewerId": 1,
            "styleId": 11,
            "abv": 7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 21,
            "name": "Emelisse Smoke Rye IPA",
            "brewerId": 1,
            "styleId": 8,
            "abv": 6.2,
            "oakAged": false,
            "tags": "rye,smoked",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 22,
            "name": "Laugar Aupa Tovarisch",
            "brewerId": 3,
            "styleId": 5,
            "abv": 11,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": 353348
        },
        {
        	"id": 23,
            "name": "Laugar Rye Strong Ale",
            "brewerId": 3,
            "styleId": 14,
            "abv": 10.5,
            "oakAged": false,
            "tags": "rye",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 24,
            "name": "Laugar Laugarian",
            "brewerId": 3,
            "styleId": 2,
            "abv": 3.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 25,
            "name": "Laugar Cypress Valley",
            "brewerId": 3,
            "styleId": 12,
            "abv": 6.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 26,
            "name": "Amager Pride",
            "brewerId": 4,
            "styleId": 5,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 199511,
            "untappdId": 304320
        },
        {
        	"id": 27,
            "name": "Amager Envy",
            "brewerId": 4,
            "styleId": 2,
            "abv": 6.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 204973,
            "untappdId": 324254
        },
        {
        	"id": 28,
            "name": "Amager ",
            "brewerId": 4,
            "styleId": 7,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 171160,
            "untappdId": 172822
        },
        {
        	"id": 29,
            "name": "Amager Greed",
            "brewerId": 4,
            "styleId": 13,
            "abv": 4.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 187411,
            "untappdId": 292146
        },
        {
        	"id": 30,
            "name": "Amager Hr. Frederiksen Niepoort",
            "brewerId": 4,
            "styleId": 5,
            "abv": 11,
            "oakAged": true,
            "tags": "barrel aged,port",
            "ratebeerId": 222840,
            "untappdId": 421433
        },
        {
        	"id": 31,
            "name": "Amager Honey Quad",
            "brewerId": 4,
            "styleId": 14,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 32,
            "name": "Amager/Cigar City Xiquic And The Hero Twins",
            "brewerId": 4,
            "styleId": 5,
            "abv": 9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 223885,
            "untappdId": 434203
        },
        {
        	"id": 33,
            "name": "Amager/Three Floyds Arctic SunStone",
            "brewerId": 4,
            "styleId": 7,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 223883,
            "untappdId": 421744
        },
        {
        	"id": 34,
            "name": "Jopen Gouds Gruit",
            "brewerId": 5,
            "styleId": 12,
            "abv": 7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 35,
            "name": "Jopen/Monarchy Grätzer",
            "brewerId": 5,
            "styleId": 9,
            "abv": 4,
            "oakAged": false,
            "tags": "smoked",
            "ratebeerId": 192894,
            "untappdId": 433141
        },
        {
        	"id": 36,
            "name": "Jopen/Monarchy Grodziskie",
            "brewerId": 5,
            "styleId": 9,
            "abv": 4,
            "oakAged": true,
            "tags": "smoked",
            "ratebeerId": 192893,
            "untappdId": 366363
        },
        {
        	"id": 37,
            "name": "Jopen/Grateful Deaf Zythos IPA",
            "brewerId": 5,
            "styleId": 2,
            "abv": 6.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 226851,
            "untappdId": 440122
        },
        {
        	"id": 38,
            "name": "Jopen Jacobus RPA",
            "brewerId": 5,
            "styleId": 8,
            "abv": 5.5,
            "oakAged": false,
            "tags": "rye",
            "ratebeerId": 151035,
            "untappdId": 151035
        },
        {
        	"id": 39,
            "name": "Jopen Frans Hals Kuit",
            "brewerId": 5,
            "styleId": 9,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 212137,
            "untappdId": 329881
        },
        {
        	"id": 40,
            "name": "Jopen SurpRYEse",
            "brewerId": 5,
            "styleId": 8,
            "abv": 7,
            "oakAged": false,
            "tags": "rye",
            "ratebeerId": -1,
            "untappdId": 437316
        },
        {
        	"id": 41,
            "name": "Jopen Koyt",
            "brewerId": 5,
            "styleId": 12,
            "abv": 8.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 6954,
            "untappdId": 6954
        },
        {
        	"id": 42,
            "name": "The Kernel India Pale Ale Simcoe Amarillo",
            "brewerId": 6,
            "styleId": 2,
            "abv": 6.9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 43,
            "name": "The Kernel Pale Ale Waimea",
            "brewerId": 6,
            "styleId": 7,
            "abv": 5.3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 44,
            "name": "The Kernel Table Beer",
            "brewerId": 6,
            "styleId": 7,
            "abv": 3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 187863,
            "untappdId": 243048
        },
        {
        	"id": 45,
            "name": "The Kernel Imperial Brown Stout Glen Spey Whisky BA",
            "brewerId": 6,
            "styleId": 5,
            "abv": 10.3,
            "oakAged": false,
            "tags": "barrel aged,wiskey",
            "ratebeerId": 222435,
            "untappdId": 392855
        },
        {
        	"id": 46,
            "name": "The Kernel Borefts Festival Special",
            "brewerId": 6,
            "styleId": 7,
            "abv": 4.3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 47,
            "name": "The Kernel Bière de Table BA",
            "brewerId": 6,
            "styleId": 17,
            "abv": 4.6,
            "oakAged": true,
            "tags": "barrel aged",
            "ratebeerId": 222436,
            "untappdId": 330677
        },
        {
        	"id": 48,
            "name": "Thornbridge Berliner Weisse",
            "brewerId": 7,
            "styleId": 3,
            "abv": 3.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 49,
            "name": "Thornbridge Jaipur",
            "brewerId": 7,
            "styleId": 2,
            "abv": 5.9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 48795,
            "untappdId": 7705
        },
        {
        	"id": 50,
            "name": "Thornbridge Calver",
            "brewerId": 7,
            "styleId": 8,
            "abv": 7.4,
            "oakAged": false,
            "tags": "rye",
            "ratebeerId": -1,
            "untappdId": 430239
        },
        {
        	"id": 51,
            "name": "Thornbridge Kacho",
            "brewerId": 7,
            "styleId": 18,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 52,
            "name": "Thornbridge Halcyon 2013",
            "brewerId": 7,
            "styleId": 2,
            "abv": 7.4,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 84956,
            "untappdId": 13845
        },
        {
        	"id": 53,
            "name": "Thornbridge Bracia BA",
            "brewerId": 7,
            "styleId": 9,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 54,
            "name": "Thornbridge St. Eriks Collaboration",
            "brewerId": 7,
            "styleId": 18,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 55,
            "name": "Alvinne Honey-B Bragot",
            "brewerId": 8,
            "styleId": 16,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 56,
            "name": "Alvinne BZN Gruit",
            "brewerId": 8,
            "styleId": 12,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 57,
            "name": "Alvinne Balthazar II",
            "brewerId": 8,
            "styleId": 14,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 58,
            "name": "Alvinne Land van Mortagne",
            "brewerId": 8,
            "styleId": 14,
            "abv": 13.9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 165719,
            "untappdId": 141500
        },
        {
        	"id": 59,
            "name": "Alvinne Foederbier",
            "brewerId": 8,
            "styleId": 3,
            "abv": 6.9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 209865,
            "untappdId": 344283
        },
        {
        	"id": 60,
            "name": "Alvinne/Stillwater Wild West",
            "brewerId": 8,
            "styleId": 3,
            "abv": 6,
            "oakAged": true,
            "tags": "barrel aged,wine,bordeaux",
            "ratebeerId": 165492,
            "untappdId": 138501
        },
        {
        	"id": 61,
            "name": "Alvinne Gaspar",
            "brewerId": 8,
            "styleId": 14,
            "abv": 8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 64244,
            "untappdId": 14571
        },
        {
        	"id": 62,
            "name": "Alvinne Melchior",
            "brewerId": 8,
            "styleId": 14,
            "abv": 11,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 54472,
            "untappdId": 59782
        },
        {
        	"id": 63,
            "name": "Alvinne Mano Negra",
            "brewerId": 8,
            "styleId": 5,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 101904,
            "untappdId": 83646
        },
        {
        	"id": 64,
            "name": "Alvinne Morpheus Dark",
            "brewerId": 8,
            "styleId": 14,
            "abv": 10.2,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 121847,
            "untappdId": 24416
        },
        {
        	"id": 65,
            "name": "Alvinne Beer Geek Wedding Batch III",
            "brewerId": 8,
            "styleId": 3,
            "abv": -1,
            "oakAged": true,
            "tags": "barrel aged",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 66,
            "name": "Alvinne Folkbier",
            "brewerId": 8,
            "styleId": 17,
            "abv": 6.3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 110986,
            "untappdId": 437107
        },
        {
        	"id": 67,
            "name": "Mikkeller Beer Geek Brunch Weasel",
            "brewerId": 8,
            "styleId": 5,
            "abv": 10.9,
            "oakAged": false,
            "tags": "coffee",
            "ratebeerId": 97034,
            "untappdId": 8391
        },
        {
        	"id": 68,
            "name": "Mikkeller Mikkeller Drink’in the Sun 13",
            "brewerId": 8,
            "styleId": 7,
            "abv": 1.4,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 211003,
            "untappdId": 411757
        },
        {
        	"id": 69,
            "name": "Mikkeller Single Hop IPA Citra",
            "brewerId": 8,
            "styleId": 2,
            "abv": 6.9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 156497,
            "untappdId": 54202
        },
        {
        	"id": 70,
            "name": "Mikkeller Green Gold Chardonnay BA",
            "brewerId": 8,
            "styleId": 2,
            "abv": 7.5,
            "oakAged": false,
            "tags": "brett,barrel aged,wine,chardonnay",
            "ratebeerId": 225596,
            "untappdId": 432534
        },
        {
        	"id": 71,
            "name": "Mikkeller Monk's Elixir",
            "brewerId": 8,
            "styleId": 14,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 72913,
            "untappdId": 25293
        },
        {
        	"id": 72,
            "name": "Mikkeller 黑 Black",
            "brewerId": 8,
            "styleId": 5,
            "abv": 17.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 83833,
            "untappdId": 70959
        },
        {
        	"id": 73,
            "name": "Mikkeller SpontanPeach",
            "brewerId": 8,
            "styleId": 3,
            "abv": 7.7,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": 202711,
            "untappdId": 355351
        },
        {
        	"id": 74,
            "name": "Mikkeller It's Alive! Chardonnay Mango BA",
            "brewerId": 8,
            "styleId": 3,
            "abv": 8,
            "oakAged": true,
            "tags": "barrel aged,wine,chardonnay,fruit",
            "ratebeerId": 202711,
            "untappdId": 356965
        },
        {
        	"id": 75,
            "name": "Mikkeller/De Molen/To Øl Bragging Braggot",
            "brewerId": 8,
            "styleId": 16,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 76,
            "name": "Toccalmatto Surfing Hop",
            "brewerId": 10,
            "styleId": 1,
            "abv": 8.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 95331,
            "untappdId": 65635
        },
        {
        	"id": 77,
            "name": "Toccalmatto Zona Cesarini Pacifica",
            "brewerId": 10,
            "styleId": 2,
            "abv": 6.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 123997,
            "untappdId": 33917
        },
        {
        	"id": 78,
            "name": "Toccalmatto Mediterranean",
            "brewerId": 10,
            "styleId": 16,
            "abv": 10.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 79,
            "name": "Toccalmatto [No Name] Gose",
            "brewerId": 10,
            "styleId": 9,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 80,
            "name": "Toccalmatto/Buxton Gruit Ale",
            "brewerId": 10,
            "styleId": 12,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 81,
            "name": "Toccalmatto/Buxton [No Name] IPA",
            "brewerId": 10,
            "styleId": 2,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 82,
            "name": "Toccalmatto Russian Imperial Stout (Wild) Sagrantino Red Wine BA",
            "brewerId": 10,
            "styleId": 5,
            "abv": 12,
            "oakAged": true,
            "tags": "barrel aged,wine,brett",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 76,
            "name": "Toccalmatto Bedda Matri Marsala BA",
            "brewerId": 10,
            "styleId": 0,
            "abv": 12,
            "oakAged": true,
            "tags": "barrel aged,wine,masala",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 76,
            "name": "Toccalmatto Vecchio Bruno Sour Emilian Red Ale BA",
            "brewerId": 10,
            "styleId": 3,
            "abv": 8,
            "oakAged": true,
            "tags": "barrel aged",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 77,
            "name": "To Øl I've Seen Bigger Than Yours",
            "brewerId": 13,
            "styleId": 0,
            "abv": 14,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": 223511,
            "untappdId": 421548
        },
        {
        	"id": 78,
            "name": "To Øl Black Malts & Body Salts",
            "brewerId": 13,
            "styleId": 8,
            "abv": 9.9,
            "oakAged": false,
            "tags": "coffee,salt",
            "ratebeerId": 216961,
            "untappdId": 386689
        },
        {
        	"id": 79,
            "name": "To Øl/Ølrepubliken Total Hubris",
            "brewerId": 13,
            "styleId": 13,
            "abv": 4.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 225232,
            "untappdId": 433040
        },
        {
        	"id": 80,
            "name": "To Øl By Udder Means Muscatel BA",
            "brewerId": 13,
            "styleId": 15,
            "abv": 7,
            "oakAged": true,
            "tags": "barrel aged,wine",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 81,
            "name": "To Øl Special Borefts Braggot Forca Victory Xtra Ekstra Edition 0.8.2",
            "brewerId": 13,
            "styleId": 16,
            "abv": -1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 82,
            "name": "Struise Weltmerz",
            "brewerId": 12,
            "styleId": 3,
            "abv": 3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 200129,
            "untappdId": 286038
        },
        {
        	"id": 83,
            "name": "Struise Ypres",
            "brewerId": 12,
            "styleId": 3,
            "abv": 7,
            "oakAged": true,
            "tags": "barrel aged,wine,bourgogne,bourbon,wild turkey",
            "ratebeerId": 195819,
            "untappdId": 286038
        },
        {
        	"id": 84,
            "name": "Struise Saint Amatus",
            "brewerId": 12,
            "styleId": 14,
            "abv": 10.5,
            "oakAged": true,
            "tags": "barrel aged,woodford reserve",
            "ratebeerId": 119174,
            "untappdId": 270216
        },
        {
        	"id": 85,
            "name": "Struise Smonk",
            "brewerId": 12,
            "styleId": 3,
            "abv": 7,
            "oakAged": false,
            "tags": "smoked",
            "ratebeerId": 226408,
            "untappdId": 443781
        },
        {
        	"id": 86,
            "name": "Struise Tsjeeses",
            "brewerId": 12,
            "styleId": 10,
            "abv": 10,
            "oakAged": false,
            "tags": "fruit",
            "ratebeerId": 64413,
            "untappdId": 43043
        },
        {
        	"id": 87,
            "name": "Struise Tsjeeses Reserva",
            "brewerId": 12,
            "styleId": 10,
            "abv": 10,
            "oakAged": true,
            "tags": "barrel aged",
            "ratebeerId": 86177,
            "untappdId": 80111
        },
        {
        	"id": 88,
            "name": "Struise/Mikkeller Elliot Brew",
            "brewerId": 12,
            "styleId": 1,
            "abv": 9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 78016,
            "untappdId": 28662
        },
        {
        	"id": 89,
            "name": "Struise Pannepot",
            "brewerId": 12,
            "styleId": 14,
            "abv": 10,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 37835,
            "untappdId": 170
        },
        {
        	"id": 90,
            "name": "Struise Pannepot Reserva",
            "brewerId": 12,
            "styleId": 14,
            "abv": 10,
            "oakAged": true,
            "tags": "barrel aged,",
            "ratebeerId": 70646,
            "untappdId": 392956
        },
        {
        	"id": 91,
            "name": "Struise Black Berry Albert",
            "brewerId": 12,
            "styleId": 5,
            "abv": 13,
            "oakAged": true,
            "tags": "fruit,barrel aged,wine,port",
            "ratebeerId": 186722,
            "untappdId": 236002
        },
        {
        	"id": 92,
            "name": "Struise Black Albert",
            "brewerId": 12,
            "styleId": 5,
            "abv": 13,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 77305,
            "untappdId": 4719
        },
        {
        	"id": 93,
            "name": "Struise Cuvée Delphine",
            "brewerId": 12,
            "styleId": 5,
            "abv": 13,
            "oakAged": true,
            "tags": "barrel aged,bourbon,four roses",
            "ratebeerId": 94955,
            "untappdId": 17653
        },
        {
        	"id": 94,
            "name": "Struise Motuecha",
            "brewerId": 12,
            "styleId": 10,
            "abv": 5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 160842,
            "untappdId": 118833
        },
        {
        	"id": 95,
            "name": "Naparbier Back in Black ",
            "brewerId": 14,
            "styleId": 8,
            "abv": 8.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 167841,
            "untappdId": 144042
        },
        {
        	"id": 96,
            "name": "Naparbier Betagarri",
            "brewerId": 14,
            "styleId": 13,
            "abv": 4.8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 227986,
            "untappdId": 441838
        },
        {
        	"id": 97,
            "name": "Naparbier ZZ+ Amber Ale",
            "brewerId": 14,
            "styleId": 2,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 165819,
            "untappdId": 174574
        },
        {
        	"id": 98,
            "name": "Naparbier Aker",
            "brewerId": 14,
            "styleId": 2,
            "abv": 6.7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 213579,
            "untappdId": 366291
        },
        {
        	"id": 99,
            "name": "Naparbier Gruit",
            "brewerId": 14,
            "styleId": 12,
            "abv": 5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 227843,
            "untappdId": 437226
        },
        {
        	"id": 100,
            "name": "Naparbier Black Rock Imperial Cacao+Coffee Porter",
            "brewerId": 14,
            "styleId": 11,
            "abv": 9,
            "oakAged": false,
            "tags": "cacao,coffee",
            "ratebeerId": 227214,
            "untappdId": -1
        },
        {
        	"id": 101,
            "name": "Naparbier 5 Titius Aniversary IPA",
            "brewerId": 14,
            "styleId": 2,
            "abv": 7.3,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 102,
            "name": "Fyne Ales Jarl",
            "brewerId": 15,
            "styleId": 6,
            "abv": 3.8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 125300,
            "untappdId": 10109
        },
        {
        	"id": 103,
            "name": "Fyne Ales Vital Spark",
            "brewerId": 15,
            "styleId": 6,
            "abv": 4.4,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 39574,
            "untappdId": 22503
        },
        {
        	"id": 104,
            "name": "Fyne Ales Fladda Rock",
            "brewerId": 15,
            "styleId": 2,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 183488,
            "untappdId": 213291
        },
        {
        	"id": 105,
            "name": "Fyne Ales Fladda Rock Belgian",
            "brewerId": 15,
            "styleId": 10,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 106,
            "name": "Fyne Ales Superior IPA",
            "brewerId": 15,
            "styleId": 1,
            "abv": 7.1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 175799,
            "untappdId": 180967
        },
        {
        	"id": 107,
            "name": "Fyne Ales Sublime Stout",
            "brewerId": 15,
            "styleId": 4,
            "abv": 6.8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 134718,
            "untappdId": 16970
        },
        {
        	"id": 108,
            "name": "Fyne Ales Sanda Black",
            "brewerId": 15,
            "styleId": 8,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 185523,
            "untappdId": 229465
        },
        {
        	"id": 109,
            "name": "Fyne Ales Sanda Blonde",
            "brewerId": 15,
            "styleId": 2,
            "abv": 5.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 185522,
            "untappdId": 229473
        },
        {
        	"id": 110,
            "name": "Fyne Ales Smoked Chilli Dark Ale",
            "brewerId": 15,
            "styleId": 18,
            "abv": 6,
            "oakAged": false,
            "tags": "smoked,cilli",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 111,
            "name": "Mont Salève Mozaic Black Bitter",
            "brewerId": 16,
            "styleId": 8,
            "abv": 3.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 185487,
            "untappdId": 176674
        },
        {
        	"id": 112,
            "name": "Mont Salève GSC Bitter",
            "brewerId": 16,
            "styleId": 6,
            "abv": 2.5,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 113,
            "name": "Mont Salève Double IPA",
            "brewerId": 16,
            "styleId": 1,
            "abv": 8,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 114,
            "name": "Mont Salève Imperial Stout",
            "brewerId": 16,
            "styleId": 5,
            "abv": 13,
            "oakAged": false,
            "tags": "",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 115,
            "name": "Mont Salève Mademoiselle French Pale Ale",
            "brewerId": 16,
            "styleId": 7,
            "abv": 6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 161044,
            "untappdId": 117706
        },
        {
        	"id": 116,
            "name": "Mont Salève Oyster Stout",
            "brewerId": 16,
            "styleId": 4,
            "abv": 5,
            "oakAged": false,
            "tags": "oyster",
            "ratebeerId": -1,
            "untappdId": -1
        },
        {
        	"id": 117,
            "name": "Rooie Dop 24/7 Session Ale",
            "brewerId": 17,
            "styleId": 7,
            "abv": 4.9,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 215382,
            "untappdId": 376326
        },
        {
        	"id": 118,
            "name": "Rooie Dop Chica Americana",
            "brewerId": 17,
            "styleId": 2,
            "abv": 7.1,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 168334,
            "untappdId": 159195
        },
        {
        	"id": 119,
            "name": "Rooie Dop Ot The Explorer",
            "brewerId": 17,
            "styleId": 1,
            "abv": 8.7,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 215383,
            "untappdId": 376327
        },
        {
        	"id": 120,
            "name": "Rooie Dop Double Oatmeal Stout",
            "brewerId": 17,
            "styleId": 5,
            "abv": 9.6,
            "oakAged": false,
            "tags": "",
            "ratebeerId": 170183,
            "untappdId": 159814
        },
        {
        	"id": 121,
            "name": "Rooie Dop Double Oatmeal Stout Bourbon BA",
            "brewerId": 17,
            "styleId": 5,
            "abv": 9.6,
            "oakAged": true,
            "tags": "barrel aged,bourbon",
            "ratebeerId": 206168,
            "untappdId": 332235
        }
    ],
    "revision": 2
}
